    export const state = {
  currentLanguage: localStorage.getItem("plamut_language") || "ru",
  currentThemeMode: localStorage.getItem("plamut_theme_mode") || "system",
  currentFilterFolder: localStorage.getItem("plamut_folder_filter") || "All",
  currentItemActionSheetId: null,
  currentCategory: null,
  currentOpenItemId: null,
  currentRelationsItemId: null,
  currentRelationsCategory: null,
  currentStatusItemId: null,
  currentSearchResults: [],
  isPublicView: false,
  currentPublicProfileName: "Library",
  searchTimer: null,
  currentFilterStatus: localStorage.getItem("plamut_status_filter") || "All",
  currentShelfSearchQuery: "",
  currentFolderModalItemId: null,
  pendingFolderSelection: "",
  currentOpenMenuItemId: null,
  currentProfileData: null,
  currentPublicProfile: null,
  activeShareToken: "",
  currentPublicShareItems: [],
  currentPublicShareState: "loading",
  publicLibraryExpanded: false,
  currentNfcContext: null,
  currentPublicLibraryMeta: { categories: [], folders: [], statuses: [] },
  currentSavedLibraryState: { saved: false, source: "none" },
  relationCache: new Map(),
  relationBuildLocks: new Map(),
  categorySearchCache: new Map(),
  categorySearchInFlight: new Map(),
  bookDescriptionCache: new Map(),
  activeCategorySearchToken: 0,
  relatedLibraryItemsCache: { userId: "", items: [], loaded: false, promise: null },
  demoData: {
    Books: [],
    Movies: [],
    Series: [],
    Anime: [],
    Manga: [],
    Blacklist: []
  }
};
